# This is a development compose file needed only for the database.
# Run the project using `pnpm run dev` and then run this command if you need to start the database manually.
# docker-compose -f docker-compose.dev.yml up

version: '3.8'

services:
  postgresql:
    image: 'bitnami/postgresql:16.6.0'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=conar
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
