name: Build and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.4

      - name: Install Dependencies
        run: pnpm install

      - name: Get Version
        id: package-version
        run: |
          echo "version=v$(node -p "require('./apps/desktop/package.json').version")" >> $GITHUB_OUTPUT

      - name: Build
        run: pnpm run build:desktop

      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          draft: true
          files: |
            apps/desktop/release/**/*.exe
            apps/desktop/release/**/*.dmg
            apps/desktop/release/**/*.AppImage

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd apps/desktop
          pnpm run publish
